<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Calculator\Calculator' shared autowired service.

return $this->privates['App\Calculator\Calculator'] = new \App\Calculator\Calculator();
