sudo: required

language: php

php:
  - '7.2'

services:
  - docker

before_install:
  - docker pull zorgik/provectus-webserver

install:
  - docker run -d -p 8080:80 zorgik/provectus-webserver
  - docker run zorgik/provectus-webserver composer install
  - docker run zorgik/provectus-webserver vendor/bin/phpunit