sudo: required

language: php

php:
  - '7.2'

services:
  - docker

before_install:
  - docker pull zorgik/provectus-webserver

install:
  - docker run -d zorgik/provectus-webserver
  - docker run zorgik/provectus-webserver vendor/bin/phpunit