<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAg68ucP\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAg68ucP/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerAg68ucP.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerAg68ucP\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerAg68ucP\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'Ag68ucP',
    'container.build_id' => '4f1743ee',
    'container.build_time' => 1554648330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAg68ucP');
