<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFAVI8hU\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFAVI8hU/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFAVI8hU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFAVI8hU\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerFAVI8hU\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'FAVI8hU',
    'container.build_id' => 'be892931',
    'container.build_time' => 1554210011,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFAVI8hU');
