<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRwH5zeU\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRwH5zeU/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerRwH5zeU.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerRwH5zeU\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerRwH5zeU\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'RwH5zeU',
    'container.build_id' => '2f402d61',
    'container.build_time' => 1554815614,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRwH5zeU');
