<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCVpifLX\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCVpifLX/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCVpifLX.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCVpifLX\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCVpifLX\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CVpifLX',
    'container.build_id' => '0ef3d886',
    'container.build_time' => 1554736381,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCVpifLX');
